version: '3.4'

services:
  webapp:
    image: cacheapi
    ports:
      - 5000
      - 80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5000;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=caltzone
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro